### ISSUE TITLE
skipping '+page@parent.svelte'

### ISSUE THREAD

**Issue by HuntClauss** [unlocomqx/intellij-svirtual-kit#1]
Hey, in sveltekit `+page@anyname.svelte` is a valid name for a +page file (https://learn.svelte.dev/tutorial/breaking-out-of-layouts).

This can be solved with a simple regex: `\+page(@.*)?\.svelte` and changes in a few places.

Example:
```kotlin
if (name.matches(Regex("\\+page(@.*)?\\.svelte")) {
    return "$route.svelte"
}
```

**Comment by unlocomqx** [comment]
Thank you for raising this issue

I will make it look like "$route@$parent.svelte" 

Here's the [new repo](https://github.com/unlocomqx/intellij-virtual-kit) btw 

Thank you

**Comment by unlocomqx** [comment]
I fixed the issue in https://github.com/unlocomqx/intellij-virtual-kit/commit/8cc05f9518cb86ef82ae106af1bea3ae7ef0493d

Thank you for your report 👋
