### ISSUE TITLE
not respecting file extension

### ISSUE THREAD

**Issue by HuntClauss** [unlocomqx/intellij-svirtual-kit#2]
You match files with .ts and .js extensions, but each file becomes a .ts file.

https://github.com/unlocomqx/intellij-svirtual-kit/blob/b6799583f8f8e7e1b91466f0cc90f341efdfef53/src/main/kotlin/net/prestalife/svirtual/helpers/SvirtualFile.kt#L13-L49

**Comment by unlocomqx** [comment]
Thank you @HuntClauss for pointing out this issue, I didn't notice it

I will replace the ts part with $extension variable

**Comment by unlocomqx** [comment]
Hi @HuntClauss, I fixed the issue in commit https://github.com/unlocomqx/intellij-virtual-kit/commit/9de20fa8e3c57ff83a9468afc117389b16439fd4

Thank you
